### ISSUE TITLE
user count problem

### ISSUE THREAD

**Issue by jameswritescode** [arifulh/listeninghall.com#3]
Hi,

Assuming the number shown in the tab is the number of people in a room, it counts itself up every time you view users list and click outside it to close it (does not do this if you click on the user list button to close it).

**Comment by arifulh** [comment]
There appears to be a lot of confusion about this, I got a few concerns about this already. The number in the title bar is supposed to show the number of messages you received while you were tabbed out, in a different window. It's not very clear, and perhaps too clunky. I will have to revisit this.
